easy_admin:
  entities:
    Profile:
      class: App\Entity\Profile
      list:
        actions:
          - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-warning'}
          - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
